# Generated by Django 5.1.3 on 2024-12-17 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='ledmode',
            field=models.CharField(choices=[('MODE 1', 'Mode 1'), ('MODE 2', 'Mode 2'), ('MODE 3', 'Mode 3')], default='MODE 1', max_length=6),
        ),
        migrations.AddField(
            model_name='devices',
            name='timezone',
            field=models.CharField(default='Asia/Ho_Chi_Minh', max_length=50),
        ),
        migrations.CreateModel(
            name='DeivceArlam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.devices')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('note', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.devices')),
            ],
        ),
    ]
