# Generated by Django 5.1.3 on 2024-12-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_devices_ledmode_devices_timezone_deivcearlam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceevent',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
