# Generated by Django 5.1.3 on 2024-12-17 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_deviceevent_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeivceArlam',
            new_name='DeviceArlam',
        ),
    ]
