# Generated by Django 5.1.3 on 2024-12-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_rename_deivcearlam_devicearlam'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='buzzermode',
            field=models.CharField(choices=[('MODE 1', 'Mode 1'), ('MODE 2', 'Mode 2'), ('MODE 3', 'Mode 3')], default='MODE 1', max_length=6),
        ),
    ]
