# Generated by Django 5.1.3 on 2024-12-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_alter_thdata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
