# Generated by Django 5.1.3 on 2024-12-20 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_alter_thdata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avg_temperature', models.FloatField()),
                ('avg_humidity', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.devices')),
            ],
        ),
    ]
