# Generated by Django 5.1.3 on 2024-12-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_aggregatedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatedata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
