# Generated by Django 5.1.3 on 2024-12-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_alter_aggregatedata_timestamp_alter_thdata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatedata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='thdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
